---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cdevent-listener
  namespace: cdevents
spec:
  serviceAccountName: cdevent-listener
  namespaceSelector:
    matchNames: ['cdevents']